import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/UI/sonner";

const font = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "ARcade",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#000000",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
