import { Nunito } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Bottombar from "@/components/Bottombar";

const font = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <div className="hidden md:block">
          <Sidebar />
        </div>

        <main className="lg:pl-64 md:pl-20 h-full pb-20">
          <div className="h-full max-w-[1056px] mx-auto pt-6">{children}</div>
        </main>

        <div className="md:hidden fixed bottom-0 left-0 w-full">
          <Bottombar />
        </div>
      </body>
    </html>
  );
}
